# Generated by Django 5.0.6 on 2026-07-08 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField()),
                ('occasion_tags', models.JSONField(blank=True, default=list)),
                ('fabric_compatibility', models.JSONField(blank=True, default=list)),
                ('price_range_min', models.IntegerField(default=0)),
                ('price_range_max', models.IntegerField(default=0)),
                ('texture_image', models.URLField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GarmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('occasion', models.CharField(blank=True, default='', max_length=100)),
                ('fabric', models.CharField(blank=True, default='', max_length=100)),
                ('image_url', models.URLField(blank=True, default='')),
                ('svg_template', models.TextField(blank=True, default='')),
                ('zone_coordinates', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavedConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=200)),
                ('neck_shape', models.CharField(blank=True, default='', max_length=50)),
                ('ref_image_url', models.URLField(blank=True, null=True)),
                ('generated_pattern_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('craft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crafttype')),
                ('garment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.garmenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
